import fs from "fs";
import path from "path";
import type { Metadata } from "next";
import FileViewerPage from "@/components/file-viewer/file-viewer-page";

import getFileMetadata from "@/utils/get-file-metadata";

/** 无可用数据时的占位参数，保证 output: export 下动态路由可构建。 */
const PLACEHOLDER = "~no-data~";

export async function generateMetadata(props: {
  params: Promise<{ contest: string; problem: string; file: string }>;
}): Promise<Metadata> {
  const { contest, problem, file } = await props.params;
  const contestFolder = decodeURIComponent(contest);
  const problemFolder = decodeURIComponent(problem);
  const fileName = decodeURIComponent(file);
  if (
    contestFolder === PLACEHOLDER ||
    problemFolder === PLACEHOLDER ||
    fileName === PLACEHOLDER
  ) {
    return { title: "File" };
  }
  const contestMetadata = getFileMetadata(
    path.join(process.cwd(), "contests", contestFolder),
    path.join(process.cwd(), "contests", contestFolder, "contest.json"),
  );
  const problemMetadata = getFileMetadata(
    path.join(process.cwd(), "contests", contestFolder, "problems", problemFolder),
    path.join(
      process.cwd(),
      "contests",
      contestFolder,
      "problems",
      problemFolder,
      "problem.json",
    ),
  );
  const contestName = String(contestMetadata.name ?? "") || contestFolder;
  const problemName = String(problemMetadata.name ?? "") || problemFolder;
  return { title: `${fileName} · ${problemName} · ${contestName}` };
}

export async function generateStaticParams() {
  const contestsDir = path.join(process.cwd(), "contests");
  if (!fs.existsSync(contestsDir)) return [{ contest: PLACEHOLDER, problem: PLACEHOLDER, file: PLACEHOLDER }];
  const contests = fs.readdirSync(contestsDir);

  const params = [];
  for (const contest of contests) {
    const problemsDir = path.join(contestsDir, contest, "problems");
    if (!fs.existsSync(problemsDir)) continue;
    const problems = fs.readdirSync(problemsDir);
    for (const problem of problems) {
      const problemPath = path.join(problemsDir, problem);
      const files = fs.readdirSync(problemPath);
      for (const file of files) {
        // Skip directories and problem metadata files
        const filePath = path.join(problemPath, file);
        if (fs.statSync(filePath).isDirectory() || file.endsWith(".json")) continue;
        params.push({
          contest,
          problem,
          file,
        });
      }
    }
  }
  // output: export 要求动态路由至少有一个静态参数；无数据时用占位参数。
  if (params.length === 0) {
    return [{ contest: PLACEHOLDER, problem: PLACEHOLDER, file: PLACEHOLDER }];
  }
  return params;
}

export default async function FilePage(props: {
  params: Promise<{ contest: string; problem: string; file: string }>;
}) {
  const params = await props.params;
  const contest = decodeURIComponent(params.contest);
  const problem = decodeURIComponent(params.problem);
  const file = decodeURIComponent(params.file);

  // 占位参数：无比赛数据时渲染提示，不读取不存在的文件。
  if (contest === PLACEHOLDER || problem === PLACEHOLDER || file === PLACEHOLDER) {
    return (
      <div className="flex min-h-screen items-center justify-center py-4">
        <div className="mx-auto w-4/5 rounded-lg border border-gray-700 p-8 text-center">
          <h1 className="text-2xl font-semibold text-slate-100">No contests yet</h1>
          <p className="mt-2 text-gray-400">
            Contest data is generated by the crawler.
          </p>
        </div>
      </div>
    );
  }

  const contestMetadata = getFileMetadata(
    path.join(process.cwd(), "contests", contest),
    path.join(process.cwd(), "contests", contest, "contest.json"),
  );

  const problemMetadata = getFileMetadata(
    path.join(process.cwd(), "contests", contest, "problems", problem),
    path.join(process.cwd(), "contests", contest, "problems", problem, "problem.json"),
  );

  const fileMetadata = getFileMetadata(
    path.join(process.cwd(), "contests", contest, "problems", problem, file),
    path.join(process.cwd(), "contests", contest, "problems", problem, file + ".json"),
  );

  return (
    <FileViewerPage
      contest={contest}
      contestMetadata={contestMetadata}
      file={file}
      fileMetadata={fileMetadata}
      problem={problem}
      problemMetadata={problemMetadata}
      fileMetadataBanner={["problem_link"]}
    />
  );
}
