name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - deploy
    paths:
      - "contests/**"
  workflow_run:
    workflows: ["Crawler Workflow"]
    types:
      - completed

jobs:
  check_contests:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check_commit.outputs.should_deploy }}
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy

      - name: Check if contests changed
        id: check_commit
        run: |
          git fetch
          git log -1 --pretty=%B > last_commit_msg.txt
          cat last_commit_msg.txt
          if grep -q '\[contests-changed\]' last_commit_msg.txt; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "Detected changes in contests directory. Will proceed with deployment."
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "No changes detected in contests directory. Will skip deployment."
          fi

  deploy:
    needs: check_contests
    if: needs.check_contests.outputs.should_deploy == 'true' || github.event_name != 'workflow_run'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy

      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy contests to public
        run: |
          mkdir -p public/contests
          cp -r contests/* public/contests/

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
