name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - deploy
    paths:
      - "contests/**"
  workflow_run:
    workflows: ["Crawler Workflow"]
    types:
      - completed

jobs:
  deploy:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy

      - name: Check if contests changed
        id: check_commit
        run: |
          git fetch
          git log -1 --pretty=%B > last_commit_msg.txt
          cat last_commit_msg.txt
          if grep -q '\[contests-changed\]' last_commit_msg.txt; then
            echo "contests_changed=true" >> $GITHUB_ENV
            echo "Detected changes in contests directory. Will proceed with deployment."
          else
            echo "contests_changed=false" >> $GITHUB_ENV
            echo "No changes detected in contests directory. Skipping deployment."
          fi

      - name: Skip deploy if contests did not change
        if: github.event_name == 'workflow_run' && env.contests_changed == 'false'
        run: |
          echo "No changes in contests, skipping deploy."
          exit 0

      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy contests to public
        run: |
          mkdir -p public/contests
          cp -r contests/* public/contests/

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
